### ISSUE TITLE
Connection not working (Link status: Inactive) on Yosemite and El Capitan

### ISSUE THREAD

**Issue by ghost** [RehabMan/OS-X-Realtek-Network#1]
This driver perfectly worked until update to Yosemite. It also **doesn't work** on El Capitan.
I have RTL8168GR chip on my board, and it is recognized by both OS X Yosemite and El Capitan as RTL8168G (I got correct Mac address of chip), but there is no connection. I got **no IP address (field is blank)**, Link status is always **Inactive**, and Link speed is always: **0Mb/s**.
I tried to full power off computer, even unplug it from power cord, but it is still not working.
I also tried to set PXE to CSM in UEFI, disable FIX_LAN in Clover, but still I got no luck.

Ethernet [RealtekRTL8111]: EEE support enabled.
Ethernet [RealtekRTL8111]: TCP/IPv4 segmentation offload enabled.
Ethernet [RealtekRTL8111]: TCP/IPv6 checksum offload enabled.
Ethernet [RealtekRTL8111]: Using interrupt mitigate value 0xcf68.
Ethernet [RealtekRTL8111]: RTL8168G/8111G: (Chipset 20) at 0xffffff81c645b000, d0:50:99:48:XX:XX

en0: flags=8863 mtu 1500
options=2b
ether d0:50:99:48:XX:XX
nd6 options=1
media: autoselect ()
status: inactive

**Comment by RehabMan** [comment]
You are not even using my build (my build uses interrupt mitigate 0x5f51).

Perhaps you should let Mieze look at your log data.

Closing as this report is unrelated to my build.
