### ISSUE TITLE
Sleep Issue. Please update to latest upstream sources

### ISSUE THREAD

**Issue by coolstar** [RehabMan/OS-X-Realtek-Network#2]
I've noticed a couple of issues with sleep on my hackintosh when I applied this kext (the latest compiled one on your bitbucket). After compiling Mieze's upstream sources manually and installing, that resolved the issue. Please update your repo to the latest upstream sources so others aren't affected by this sleep issue as well.

**Comment by RehabMan** [comment]
Define 'couple of issues'.

**Comment by coolstar** [comment]
When the system is put to sleep, it either hangs on suspend, or it does suspend but wakes instantly. Without the kexl (or with the newer next), it sleeps and wakes properly.

**Comment by RehabMan** [comment]
It is probably related to your BIOS settings for "wake on LAN".
I will eventually update the bitbucket/github, but I will need time to test it with my hardware...
I will go ahead and push the merged source to github though.
Those that want to build it can do so.

**Comment by RehabMan** [comment]
Updated build.
