### ISSUE TITLE
It is have problem with 10.13 high sierra 

### ISSUE THREAD

**Issue by sarus72rus** [RehabMan/OS-X-Realtek-Network#3]
Anonymous UUID:       86EDECA9-C5F8-9D70-0FDE-8A9AED06512C

Sun Oct  1 09:13:04 2017

*** Panic Report ***
panic(cpu 2 caller 0xffffff800a38a611): Kernel trap at 0xffffff7f8cad8edb, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff802304abd0, CR3: 0x0000000013a47000, CR4: 0x00000000001627e0
RAX: 0x0000000000000000, RBX: 0xffffff81abc07000, RCX: 0x0000000000000bd0, RDX: 0x0000000000000100
RSP: 0xffffff91fe3fbcb0, RBP: 0xffffff91fe3fbd40, RSI: 0xffffff802f250e00, RDI: 0x00000000000000bd
R8:  0x0000000000000000, R9:  0x0000000000000002, R10: 0x000004e4e0ba55bb, R11: 0x0000000000000000
R12: 0xffffff81abc07000, R13: 0xffffff802304a000, R14: 0xffffff81abc07000, R15: 0x0000000000000000
RFL: 0x0000000000010202, RIP: 0xffffff7f8cad8edb, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff802304abd0, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff91fe3fb770 : 0xffffff800a26d366 
0xffffff91fe3fb7b0 : 0xffffff800a398494 
0xffffff91fe3fb7f0 : 0xffffff800a38a429 
0xffffff91fe3fb870 : 0xffffff800a21f190 
0xffffff91fe3fb890 : 0xffffff800a26cd8c 
0xffffff91fe3fb9c0 : 0xffffff800a26cafc 
0xffffff91fe3fba20 : 0xffffff800a38a611 
0xffffff91fe3fbba0 : 0xffffff800a21f190 
0xffffff91fe3fbbc0 : 0xffffff7f8cad8edb 
0xffffff91fe3fbd40 : 0xffffff7f8cad8c42 
0xffffff91fe3fbd60 : 0xffffff7f8ae0f9de 
0xffffff91fe3fbd90 : 0xffffff800a8a5878 
0xffffff91fe3fbe00 : 0xffffff7f8ae0fa48 
0xffffff91fe3fbe60 : 0xffffff7f8ae13cbc 
0xffffff91fe3fbee0 : 0xffffff800a515ee5 
0xffffff91fe3fbfa0 : 0xffffff800a21c4f7 
      ****Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.3)[EF78DFDF-AA20-3533-B1BD-EFC423E72F7C]@0xffffff7f8ae07000->0xffffff7f8ae33fff
         com.insanelymac.RealtekRTL8111(2.2.1)[07D64653-7867-3C3A-837B-E491B33C21B7]@0xffffff7f8ca79000->0xffffff7f8cadffff
            dependency: com.apple.iokit.IONetworkingFamily(3.3)[EF78DFDF-AA20-3533-B1BD-EFC423E72F7C]@0xffffff7f8ae07000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF1517A2-32C4-328E-9890-03E6C546604A]@0xffffff7f8aa94000****

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=no kext-dev-mode=1 

Mac OS version:
17A365

Kernel version:
Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64
Kernel UUID: B84FDEFC-9081-35CE-8C51-25A9583AACDE
Kernel slide:     0x000000000a000000
Kernel text base: 0xffffff800a200000
__HIB  text base: 0xffffff800a100000
System model name: iMac14,1 (Mac-031B6874CF7F642A)

System uptime in nanoseconds: 5381069512379
last loaded kext at 243572131526: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8cae0000, size 69632)
last unloaded kext at 304449770573: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8cae0000, size 61440)
loaded kexts:
com.insanelymac.RealtekRTL8111	2.2.1
org.netkas.driver.FakeSMC	1426
com.rehabman.driver.USBInjectAll	0.6.2
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleHDA	280.12
com.apple.AGDCPluginDisplayMetrics	3.16.19
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleIntelHD5000Graphics	10.2.8
com.apple.iokit.IOBluetoothSerialManager	6.0.0f7
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.Apple16X50ACPI	3.2
com.apple.driver.eficheck	1
com.apple.AVEBridge	1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelFramebufferAzul	10.2.8
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.apfs	748.1.46
com.apple.filesystems.hfs.kext	407.1.3
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.kext.triggers	1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.iokit.IOTimeSyncFamily	600.15
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOBluetoothFamily	6.0.0f7
com.apple.AppleGPUWrangler	3.16.19
com.apple.driver.Apple16X50Serial	3.2
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IONDRVSupport	517.17
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.AppleGraphicsDeviceControl	3.16.19
com.apple.iokit.IOAcceleratorFamily2	373
com.apple.iokit.IOSurface	209
com.apple.iokit.IOGraphicsFamily	517.17
com.apple.driver.AppleUSBAudio	310.35
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOAHCIBlockStorage	301.1.2
com.apple.iokit.IONetworkingFamily	3.3
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.1.2
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140
com.apple.iokit.IOSCSIBlockCommandsDevice	404
com.apple.iokit.IOSCSIArchitectureModelFamily	404
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: iMac14,1, BootROM IM141.0123.B00, 4 processors, Intel Core i5, 3,19 GHz, 16 GB, SMC 2.14f24
Graphics: Intel HD Graphics 4600, Intel HD Graphics 4600, Built-In
Memory Module: BANK 0/DIMM1, 8 GB, DDR3, 1600 MHz, AMD, -
Memory Module: BANK 1/DIMM1, 8 GB, DDR3, 1600 MHz, AMD, -
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 850 EVO 250GB, 250,06 GB
Serial ATA Device: ST31000524AS, 1 TB
USB Device: USB 3.0 Bus
USB Device: USB Keyboard
USB Device: ZELOTES GAME MOUSE
USB Device: USB Microphone UM-1
USB Device: USB 2.0 Camera
USB Device: USB 2.0 Bus
USB Device: Hub
Thunderbolt Bus:

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
