### ISSUE TITLE
"Version control conflict marker in file" error

### ISSUE THREAD

**Issue by iandrewt** [RehabMan/OS-X-Realtek-Network#4]
I tried compiling this and Xcode 9.1 (running macOS 10.13.1 with the same SDK, I'm aware this isn't in your build environment list) found a version control conflict marker and errored out. Link is to where the marker was found

https://github.com/RehabMan/OS-X-Realtek-Network/blob/2b00e35a53f420baf90960c8d65614f2eb52e4fd/RealtekRTL8111/RealtekRTL8111.cpp#L1794

**Comment by RehabMan** [comment]
Crazy.  No idea why it was still building here.  Merge mistake fixed.
